name: rrwnet
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgomp=15.1.0=h767d61c_5
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.53.1
      - fsspec==2024.2.0
      - idna==3.6
      - imageio==2.33.1
      - jinja2==3.1.3
      - joblib==1.5.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pandas==2.3.3
      - pillow==10.2.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.31.0
      - scikit-image==0.22.0
      - scikit-learn==1.5.1
      - scipy==1.12.0
      - six==1.16.0
      - sympy==1.12
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2024.1.30
      - torch==2.2.0
      - torchvision==0.17.0
      - triton==2.2.0
      - typing-extensions==4.9.0
      - tzdata==2025.2
      - urllib3==2.2.0
prefix: /SSD/home/gabriel/miniforge3/envs/rrwnet
