name: /SSD/home/cbg/miniconda3/retinalysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=4_kmp_llvm
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - bcrypt=5.0.0=py310hd8f68c5_1
  - boto3=1.42.0=pyhd8ed1ab_0
  - botocore=1.41.6=pyhd8ed1ab_0
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h34a4b09_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - coin-or-cbc=2.10.12=h4d16d09_4
  - coin-or-cgl=0.60.9=hc46dffc_6
  - coin-or-clp=1.17.10=hc03379b_3
  - coin-or-osi=0.108.11=hf4fecb4_8
  - coin-or-utils=2.11.12=hc93afbd_7
  - coincbc=2.10.12=4_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - comm=0.2.3=pyhe01879c_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cryptography=46.0.3=py310hed992bd_0
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.13.1.26=hbcb9cd8_0
  - datrie=0.8.3=py310h7c4b9e2_0
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.22.3=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_1
  - dropbox=12.0.2=pyhd8ed1ab_1
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filechunkio=1.8=py_2
  - filelock=3.20.0=pyhd8ed1ab_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-api-python-client=2.187.0=pyh332efcf_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.1=pyhd8ed1ab_0
  - google-cloud-core=2.5.0=pyhd8ed1ab_0
  - google-cloud-storage=3.6.0=pyhcf101f3_0
  - google-crc32c=1.7.1=py310hf432777_1
  - google-resumable-media=2.8.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - grpcio=1.74.1=py310h8f3b6d6_1
  - grpcio-status=1.74.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httplib2=0.31.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - invoke=2.2.1=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - legacy-cgi=2.6.4=pyhcf101f3_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=36_h5875eb1_mkl
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=36_hfef963f_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.13.1.26=hf7e9902_0
  - libcudnn-dev=9.13.1.26=h58dd1b1_0
  - libcudss=0.6.0.5=h58dd1b1_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.74.1=h3288cfb_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h5e43f62_mkl
  - liblapacke=3.9.0=36_hdba1596_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=ha7672b3_3
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.9.86=h5888daf_1
  - libnvjpeg=12.4.0.76=h5888daf_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libtorch=2.7.1=cuda129_mkl_h9562ed8_304
  - libudev1=257.9=h085a93f_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.2=h4922eb0_3
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2024.2.2=ha770c72_17
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.17.0=py310h03d9f68_1
  - pandas=2.3.3=py310h0158d43_2
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.8=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=6.31.1=py310ha36e12e_2
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulp=2.7.0=py310hff52083_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.1=py310h7c4b9e2_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.1=pyhcf101f3_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-irodsclient=3.1.1=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.7.1=cuda129_mkl_py310_hecdad2d_304
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=59.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - setuptools-scm=9.2.2=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - slacker=0.14.0=pyhd8ed1ab_1
  - sleef=3.9.0=ha0421bc_0
  - smart_open=7.5.0=pyhcf101f3_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.13.0=hb60516a_3
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - toposort=1.10=pyhd8ed1ab_1
  - torchvision=0.23.0=cuda129_py310_ha17f1f0_1
  - torchvision-extra-decoders=0.0.2=py310h18ecd09_3
  - tornado=6.5.2=py310h7c4b9e2_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=2.0.1=py310h7c4b9e2_1
  - x265=3.5=h924138e_3
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - yte=1.9.4=pyhd8ed1ab_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohttp==3.13.0
      - albumentations==1.3.1
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - idna==3.10
      - imageio==2.37.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning==2.1.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - monai==1.2.0
      - multidict==6.7.0
      - nbstripout==0.3.9
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pillow==9.5.0
      - propcache==0.4.1
      - pydicom==2.3.1
      - pytorch-lightning==2.5.5
      - qudida==0.0.4
      - referencing==0.36.2
      - rpds-py==0.27.1
      - rtnls-enface==0.1.0
      - rtnls-fundusprep==0.1.0
      - rtnls-inference==0.1.0
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sknw==0.14
      - sortedcontainers==2.4.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.8.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - triton==3.4.0
      - vascx==0.0.0
prefix: /SSD/home/cbg/miniconda3/retinalysis
